language: c++
dist: focal

before_install:
  - sudo apt-get install make git-core cmake python -y
  - export VITASDK=/usr/local/vitasdk
  - export PATH=$VITASDK/bin:$PATH # add vitasdk tool to $PATH
  - sh .travis/install_toolchain.sh

script:
  - sh .travis/build.sh
