name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest
    
    steps:
    - name: Update git
      run: |
        apk update
        apk add git

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Build
      run: |
        mkdir build && cd build && cmake ..
        make

    - uses: actions/upload-artifact@v4
      with:
        name: VITAlbum.vpk
        path: build/VITAlbum.vpk
